# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160518_0707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ['index', 'id'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AddField(
            model_name='article',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Catalog', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='index',
            field=models.IntegerField(default=999, verbose_name='分类的排序'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='name',
            field=models.CharField(default=None, max_length=30, verbose_name='分类名称'),
        ),
    ]
