# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160518_0716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ['index', 'id'], 'verbose_name': '目录', 'verbose_name_plural': '目录'},
        ),
        migrations.AlterField(
            model_name='catalog',
            name='index',
            field=models.IntegerField(default=999, verbose_name='目录的排序'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(default=None, max_length=30, verbose_name='目录名称'),
        ),
    ]
