# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160518_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30, verbose_name='栏目名称')),
                ('index', models.IntegerField(default=999, verbose_name='栏目的排序')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': '栏目',
                'ordering': ['index', 'id'],
                'verbose_name_plural': '栏目',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Catalog', verbose_name='目录'),
        ),
    ]
