# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_slogan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slogan',
            options={'verbose_name': '标语', 'verbose_name_plural': '标语'},
        ),
    ]
